Class {
	#name : 'CapellaFunctionalExchange',
	#superclass : 'CapellaObject',
	#instVars : [
		'source',
		'target',
		'name'
	],
	#category : 'Capella',
	#package : 'Capella'
}

{ #category : 'accessing' }
CapellaFunctionalExchange >> name [

	^ name
]

{ #category : 'accessing' }
CapellaFunctionalExchange >> name: anObject [

	name := anObject
]

{ #category : 'accessing' }
CapellaFunctionalExchange >> source [

	^ source
]

{ #category : 'accessing' }
CapellaFunctionalExchange >> source: anObject [

	source := anObject
]

{ #category : 'accessing' }
CapellaFunctionalExchange >> target [

	^ target
]

{ #category : 'accessing' }
CapellaFunctionalExchange >> target: anObject [

	target := anObject
]
