Class {
	#name : 'CapellaFunctionalChainInvolvment',
	#superclass : 'CapellaObject',
	#instVars : [
		'activity',
		'source',
		'target'
	],
	#category : 'Capella',
	#package : 'Capella'
}

{ #category : 'accessing' }
CapellaFunctionalChainInvolvment >> activity [

	^ activity
]

{ #category : 'accessing' }
CapellaFunctionalChainInvolvment >> activity: anObject [

	activity := anObject
]

{ #category : 'accessing' }
CapellaFunctionalChainInvolvment >> source [

	^ source
]

{ #category : 'accessing' }
CapellaFunctionalChainInvolvment >> source: anObject [

	source := anObject
]

{ #category : 'accessing' }
CapellaFunctionalChainInvolvment >> target [

	^ target
]

{ #category : 'accessing' }
CapellaFunctionalChainInvolvment >> target: anObject [

	target := anObject
]
