Class {
	#name : 'CapellaImporter',
	#superclass : 'Object',
	#instVars : [
		'document',
		'model'
	],
	#category : 'Capella',
	#package : 'Capella'
}

{ #category : 'accessing' }
CapellaImporter >> document [

	^ document
]

{ #category : 'accessing' }
CapellaImporter >> document: anObject [

	document := anObject
]

{ #category : 'accessing' }
CapellaImporter >> model [

	^ model
]
