Class {
	#name : 'OldCapellaFunctionalChainInvolvment',
	#superclass : 'OldCapellaObject',
	#instVars : [
		'activity',
		'source',
		'target'
	],
	#category : 'Capella-import',
	#package : 'Capella',
	#tag : 'import'
}

{ #category : 'accessing' }
OldCapellaFunctionalChainInvolvment >> activity [

	^ activity
]

{ #category : 'accessing' }
OldCapellaFunctionalChainInvolvment >> activity: anObject [

	activity := anObject
]

{ #category : 'accessing' }
OldCapellaFunctionalChainInvolvment >> source [

	^ source
]

{ #category : 'accessing' }
OldCapellaFunctionalChainInvolvment >> source: anObject [

	source := anObject
]

{ #category : 'accessing' }
OldCapellaFunctionalChainInvolvment >> target [

	^ target
]

{ #category : 'accessing' }
OldCapellaFunctionalChainInvolvment >> target: anObject [

	target := anObject
]
