Class {
	#name : 'OldCapellaFunctionalExchange',
	#superclass : 'OldCapellaObject',
	#instVars : [
		'source',
		'target',
		'name'
	],
	#category : 'Capella-import',
	#package : 'Capella',
	#tag : 'import'
}

{ #category : 'accessing' }
OldCapellaFunctionalExchange >> name [

	^ name
]

{ #category : 'accessing' }
OldCapellaFunctionalExchange >> name: anObject [

	name := anObject
]

{ #category : 'accessing' }
OldCapellaFunctionalExchange >> source [

	^ source
]

{ #category : 'accessing' }
OldCapellaFunctionalExchange >> source: anObject [

	source := anObject
]

{ #category : 'accessing' }
OldCapellaFunctionalExchange >> target [

	^ target
]

{ #category : 'accessing' }
OldCapellaFunctionalExchange >> target: anObject [

	target := anObject
]
