Class {
	#name : 'OldCapellaTimeLapses',
	#superclass : 'OldCapellaObject',
	#instVars : [
		'start',
		'finish',
		'relatedAbstractFunction'
	],
	#category : 'Capella-import',
	#package : 'Capella',
	#tag : 'import'
}

{ #category : 'accessing' }
OldCapellaTimeLapses >> finish [

	^ finish
]

{ #category : 'accessing' }
OldCapellaTimeLapses >> finish: anObject [

	finish := anObject
]

{ #category : 'accessing' }
OldCapellaTimeLapses >> relatedAbstractFunction [

	^ relatedAbstractFunction
]

{ #category : 'accessing' }
OldCapellaTimeLapses >> relatedAbstractFunction: anObject [

	relatedAbstractFunction := anObject
]

{ #category : 'accessing' }
OldCapellaTimeLapses >> start [

	^ start
]

{ #category : 'accessing' }
OldCapellaTimeLapses >> start: anObject [

	start := anObject
]
