Class {
	#name : 'OldCapellaSystemMission',
	#superclass : 'OldCapellaObject',
	#instVars : [
		'name',
		'involvments',
		'capabilities'
	],
	#category : 'Capella-import',
	#package : 'Capella',
	#tag : 'import'
}

{ #category : 'accessing' }
OldCapellaSystemMission >> capabilities [

	^ capabilities
]

{ #category : 'accessing' }
OldCapellaSystemMission >> capabilities: anObject [

	capabilities := anObject
]

{ #category : 'accessing' }
OldCapellaSystemMission >> involvments [

	^ involvments
]

{ #category : 'accessing' }
OldCapellaSystemMission >> involvments: anObject [

	involvments := anObject
]

{ #category : 'accessing' }
OldCapellaSystemMission >> name [

	^ name
]

{ #category : 'accessing' }
OldCapellaSystemMission >> name: anObject [

	name := anObject
]
