Class {
	#name : 'NeoExample',
	#superclass : 'Object',
	#category : 'Capella-Requirements-Neo-Deprecated',
	#package : 'Capella-Requirements',
	#tag : 'Neo-Deprecated'
}

{ #category : 'as yet unclassified' }
NeoExample >> inspectNeoRequeriment [

	<script:
	'(NeoRequirementsRepositoryBuilder new forPragma: #neoreq) inspect'>
	
]

{ #category : 'as yet unclassified' }
NeoExample >> req001 [

	<neoreq: #req_001>
	
]

{ #category : 'as yet unclassified' }
NeoExample >> req002 [

	<neoreq: #req_002>
	
]
